services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: pusaka
      POSTGRES_PASSWORD: pusaka_dev_only
      POSTGRES_DB: pusaka_bangli
    ports:
      - '5434:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
